#!/bin/bash
#
# Usage: dis-pack [OPTION]... [FILE]
# Read a message from FILE or standard input and pack it.
#  TODO: add support for encryption targeting a group
#  TODO: add support for more key value pairs than just content
#
#  -s, --sign                  sign message
#  -S, --signatory [USER-ID]   use USER-ID as signer, implies -s
#  -e, --encrypt [USER-ID]     encrypt for USER-ID (multiples okay)
#
. $(dirname $0)/dis-common

## Parse command line arguments
SIGN=""; SIGNATORY=""; RECIPIENTS=(); FILE="";
if ! options=$(getopt -o sS:e: -l sign,signatory:,encrypt: -- "$@");then
    help; exit 1;
fi
set -- $options
while [ $# -gt 0 ];do
    case $1 in
        -s|--sign) SIGN="yes";;
        -S|--signatory)
            if [ -z "$SIGNATORY" ];then
                SIGNATORY="$2"; shift;
            else
                error "can only specify 1 signatory";
            fi;;
        -e|--encrypt) RECIPIENTS+="$2"; shift;;
        (--) shift; break;;
        (-*) error "$0: error -- unrecognized option $1";;
        (*)  break;;
    esac
    shift
done
CONTENT=$(if [ -z "$FILE" ];then cat -;else cat "$FILE";fi|quote)

## Build the output
echo -n "{"

# Hash
HASH=$(sha1 $CONTENT)
echo -n " \"keys\":[\"content\"],"
echo -n " \"hash\":\"$HASH\","

# Sign
if [ ! -z "$SIGN" ];then

    # Signatory
    SIGNATORY=$(gpg_name $SIGNATORY)
    echo -n " \"signatory\":\"$SIGNATORY\","

    # Signature
    SIGNATURE=$(sign "$SIGNATORY" "$CONTENT")
    echo -n " \"signature\":$SIGNATURE,"

fi

# TODO: Encrypted for recipients
if [ -z $RECIPIENTS ];then
    echo -n " \"content\":$CONTENT"
else
    error "Encryption for recipients is not yet supported.";
fi

echo    " }"
