#!/bin/bash
#
# Usage: not executable
# Common functionality to be used in all dis scripts
#
SCRIPT="$0"
help(){
    HELP_TEXT=$(cat "$SCRIPT" \
        |sed '/^[^#]/q' \
        |head -n -1 \
        |tail -n +3 \
        |sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' \
        |cut -c3-)
    echo "$HELP_TEXT"
    exit 1
}
if echo "$1"|grep "^\-\?\-h" >/dev/null;then help; fi

error(){ echo $@ 1>&2; exit 1; }

gpg_name(){
    # TODO: setup a mapping between custom user names and gpg IDs
    local signatory="$1";
    if [ -z "$signatory" ];then
        if [ -z "$GPGKEY" ];then
            echo "no default GPG key set in GPGKEY";
        else
            signatory="$GPGKEY";
        fi
    fi
    echo "$signatory"
}

sign(){
    local gpg_name="$1"; local contents="$2";
    echo "$content"|gpg --armor --detach-sign --local-user "$gpg_name"|quote
}

quote(){
    jshon -s "$(if [ -z "$1" ];then cat -;else echo "$1";fi)" 2>/dev/null
}

sha1(){
    local content="$@";
    local length=$(expr length "$content");
    echo "\"content\" $length $content"|sha1sum|cut -c-40
}
