#!/bin/bash
#
# Usage: dis-endpoint end-point
# Return the address of an endpoint
#
# end-point       - an end point 
#
. $(dirname $0)/dis-common

NAME="$1"

cat "$DATABASE"|grep "^$NAME"|awk '{print $2,$3}'
