#!/bin/bash
#
# Usage: dis-save [OPTION] [FILE]
# Save a message from FILE or standard input to the database.
#
#  -d, --database     specify database file (default $DIS_BASE)
#
. $(dirname $0)/dis-common

## Parse command line arguments
BASE="$DIS_BASE"
options -o d: -l database: -- "$@"
while [ $# -gt 0 ];do
    case $1 in
        -d|--database) BASE="$2"; shift;;
        (--) shift; break;;
        (-*) error "$0: error -- unrecognized option $1";;
        (*)  break;;
    esac
    shift
done
if [ -z "$BASE" ];then
    error "must specify a database with -d or the DIS_BASE env variable"
fi
CONTENT=$(if [ -z "$1" ];then cat -;else cat "$1";fi)

## Add to the database
echo "$CONTENT"|to_base >> "$BASE"
