#!/bin/bash
#
# Usage: dis-simple-pack [sender]
# Takes the name of a as an argument, and a message on STDIN
#
. $(dirname $0)/dis-common
if [ -z "$1" ];then help;else USER="$1";fi

echo -n "{ 'user':'$USER' 'content':'"
cat -
echo "'}"
