#!/bin/bash
#
# Usage: dis-send [OPTIONS] [FILE]
# Read message from FILE or standard input and send to HOST:PORT
#  TODO: should there be a handshake or error code for failure?
#
# -s, --server [HOST]      the host to send to (default:localhost)
# -p, --port [PORT]        the port on the host (default:4444)
#
. $(dirname $0)/dis-common
HOST=localhost; PORT=4444;
options -o s:p: -l server:,port: -- "$@"
while [ $# -gt 0 ];do
    case $1 in
        -s|--server) HOST="$2"; shift;;
        -p|--port) port="$2"; shift;;
        (--) shift; break;;
        (-*) error "$0: error -- unrecognized option $1";;
        (*)  break;;
    esac
    shift
done
CONTENT=$(if [ -z "$1" ];then cat -;else cat "$1";fi)

echo "$CONTENT"|gzip|netcat -c "$HOST" "$PORT"
