#!/bin/bash
#
# just playing with getopt
#
. $(dirname $0)/dis-common
foo="unset"
bar="unset" # <- has required arg.
baz="unset"
if ! options=$(getopt -o fb:z -l foo,bar:,baz -- "$@");then
    exit 1;
fi

set -- $options

while [ $# -gt 0 ];do
    case $1 in
        -f|--foo) foo="set";;
        -b|--bar) bar="$2"; shift;;
        -z|--baz) baz="set";;
        (--) shift; break;;
        (-*) echo "$0: error -- unrecognized option %1" 2>&1; exit 1;;
        (*)  break;;
    esac
    shift
done

echo " foo:$foo"
echo " bar:$bar"
echo " baz:$baz"
echo "rest:$@"
