#!/bin/bash
#
# Usage: dis-remote [OPTIONS] CMD [args]
# communicate with a remote server
#
# CMD
#   grep    takes key=regexp pairs and returns matching messages
#   pull    takes one or more hash prefixes and returns the messages
#   push    takes a message hash and uploads it to the server
#
# OPTIONS
#   -s, --server [HOST]      the host to send to (default:localhost)
#   -p, --port [PORT]        the port on the host (default:4444)
#   -j, --json               leave the results as raw JSON
#
. $(dirname $0)/dis-common
HOST=localhost; PORT=4444;
options -o s:p:j -l server:,port:,json -- "$@"
while [ $# -gt 0 ];do
    case $1 in
        -s|--server) HOST="$2"; shift;;
        -p|--port) PORT="$2"; shift;;
        -j|--json) JSON="yes";;
        (--) shift; break;;
        (-*) error "$0: error -- unrecognized option $1";;
        (*)  break;;
    esac
    shift
done

cmd=$1; shift
if [ "$1" == "-" ];then args="$(cat -)";else args="$@";fi

run(){
    case $cmd in
        pull) echo -E "pull $(to_array  $args)";;
        push) echo -E "push $(to_array  $args)";;
        grep) echo -E "grep $(to_object $args)";;
    esac|netcat "$HOST" "$PORT"
}

RESULT="$(run)"

if [ ! -z "$JSON" ];then
    echo "$RESULT"
else
    case $cmd in
        pull)
            for i in $(seq $(echo "$RESULT"|jshon -l));do
                show_msg "$(echo "$RESULT"|jshon -e $i)"
            done|less;;
        push) echo "$RESULT";;
        grep) echo "$RESULT"|jshon -a -u;;
    esac
fi
